name: PurgePlugin
version: 0.2
main: com.clashnia.plugins.purge.PurgePlugin
author: TheFatDemon
commands:
  purge:
    description: Main Purge Command
    permission: purge.basic.purge
  stats:
    description: Check Current Stats
    permission: purge.basic.stats